# Generated by Django 4.2.28 on 2026-03-17 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ALTERAR_SENHA', 'Alteração de Senha'), ('VINCULAR_GOVBR', 'Vinculação Gov.br'), ('CRIAR_RECEITA', 'Criação de Receita'), ('EDITAR_RECEITA', 'Edição de Receita'), ('DELETAR_RECEITA', 'Exclusão de Receita'), ('ASSINAR_RECEITA', 'Assinatura de Receita (Gov.br)'), ('ENVIAR_RECEITA', 'Envio de Receita ao Paciente'), ('CRIAR_PRONTUARIO', 'Criação de Prontuário'), ('EDITAR_PRONTUARIO', 'Edição de Prontuário'), ('APROVAR_SOLICITACAO', 'Aprovação de Solicitação'), ('REJEITAR_SOLICITACAO', 'Rejeição de Solicitação'), ('EXPORT_RELATORIO', 'Exportação de Relatório'), ('UPLOAD_CERTIFICADO', 'Upload de Certificado'), ('DELETAR_CERTIFICADO', 'Remoção de Certificado'), ('ACESSO_NEGADO', 'Tentativa de Acesso Negada')], db_index=True, max_length=50, verbose_name='Ação')),
                ('modelo', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Modelo afetado')),
                ('pk_objeto', models.CharField(blank=True, max_length=100, verbose_name='ID do objeto afetado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('dados_extra', models.JSONField(blank=True, help_text='Snapshot antes/depois da alteração ou dados relevantes.', null=True, verbose_name='Dados adicionais')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data/Hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'acao'], name='trathea_cor_usuario_1a0a42_idx'), models.Index(fields=['modelo', 'pk_objeto'], name='trathea_cor_modelo_bedbf5_idx')],
            },
        ),
    ]
