# Generated by Django 4.2.28 on 2026-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trathea_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ALTERAR_SENHA', 'Alteração de Senha'), ('VINCULAR_GOVBR', 'Vinculação Gov.br'), ('CRIAR_RECEITA', 'Criação de Receita'), ('EDITAR_RECEITA', 'Edição de Receita'), ('DELETAR_RECEITA', 'Exclusão de Receita'), ('ASSINAR_RECEITA', 'Assinatura de Receita (Gov.br)'), ('ENVIAR_RECEITA', 'Envio de Receita ao Paciente'), ('CRIAR_PRONTUARIO', 'Criação de Prontuário'), ('EDITAR_PRONTUARIO', 'Edição de Prontuário'), ('APROVAR_SOLICITACAO', 'Aprovação de Solicitação'), ('REJEITAR_SOLICITACAO', 'Rejeição de Solicitação'), ('EXPORT_RELATORIO', 'Exportação de Relatório'), ('UPLOAD_CERTIFICADO', 'Upload de Certificado'), ('DELETAR_CERTIFICADO', 'Remoção de Certificado'), ('ACESSO_NEGADO', 'Tentativa de Acesso Negada'), ('CRIAR', 'Criação de Registro'), ('ATUALIZAR', 'Atualização de Dados'), ('DELETAR', 'Exclusão de Registro'), ('ALTERAR_DADOS_CRITICOS', 'Alteração de Dados Críticos (CRM/CNPJ)')], db_index=True, max_length=50, verbose_name='Ação'),
        ),
    ]
