# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medico', 'Médico'), ('clinica', 'Clínica'), ('secretaria', 'Secretaria')], max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em Análise'), ('aprovada', 'Aprovada'), ('rejeitada', 'Rejeitada')], default='pendente', max_length=20)),
                ('dados_adicionais', models.JSONField(help_text='CRM para médicos, CNPJ para clínicas, etc.', verbose_name='Dados da solicitação')),
                ('documento_comprobatorio', models.FileField(blank=True, null=True, upload_to='solicitacoes/documentos/', verbose_name='Documento comprobatório')),
                ('motivo_rejeicao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Solicitação de Cadastro',
                'verbose_name_plural': 'Solicitações de Cadastro',
                'ordering': ['-created_at'],
            },
        ),
    ]
