# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='avaliado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitacoes_avaliadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitacaocadastro',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_cadastro', to=settings.AUTH_USER_MODEL),
        ),
    ]
