# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm', models.CharField(help_text='Número do Conselho Regional de Medicina.', max_length=20, unique=True, verbose_name='CRM')),
                ('crm_estado', models.CharField(help_text='UF do CRM. Ex: SP, RJ, MG.', max_length=2, verbose_name='Estado do CRM')),
                ('especialidade', models.CharField(max_length=100, verbose_name='Especialidade médica')),
                ('sub_especialidades', models.CharField(blank=True, help_text='Separadas por vírgula.', max_length=300, verbose_name='Sub-especialidades')),
                ('assinatura_img', models.ImageField(blank=True, help_text='Assinatura manuscrita digitalizada (PNG/JPEG).', null=True, upload_to='assinaturas/', verbose_name='Imagem da assinatura')),
                ('govbr_sub', models.CharField(blank=True, help_text='Identificador único do médico no Gov.br (hash CPF).', max_length=200, verbose_name='Subject Gov.br')),
                ('is_govbr_linked', models.BooleanField(default=False, help_text='True quando o médico autorizou assinatura via Gov.br.', verbose_name='Gov.br vinculado')),
                ('bio', models.TextField(blank=True, help_text='Apresentação profissional do médico.', verbose_name='Biografia')),
                ('atende_convenio', models.BooleanField(default=True, verbose_name='Atende convênio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinica_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicos_principais', to='clinica_app.clinica', verbose_name='Clínica principal')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'medico'}, on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'ordering': ['user__nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('hora_inicio', models.TimeField(verbose_name='Hora de início')),
                ('hora_fim', models.TimeField(verbose_name='Hora de término')),
                ('duracao_consulta_min', models.PositiveIntegerField(default=30, verbose_name='Duração da consulta (min)')),
                ('ativo', models.BooleanField(default=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='medico_app.medico')),
            ],
            options={
                'verbose_name': 'Disponibilidade',
                'verbose_name_plural': 'Disponibilidades',
                'ordering': ['dia_semana', 'hora_inicio'],
                'unique_together': {('medico', 'dia_semana', 'hora_inicio')},
            },
        ),
    ]
