# Generated by Django 4.2.28 on 2026-03-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceituarioConfig',
            fields=[
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='receituario_config', serialize=False, to='medico_app.medico')),
                ('logotipo_clinica', models.ImageField(blank=True, null=True, upload_to='receituarios/logos/')),
                ('cabecalho', models.TextField(blank=True, help_text='Texto do cabeçalho da receita.')),
                ('rodape', models.TextField(blank=True, help_text='Texto do rodapé da receita.')),
                ('fonte_nome', models.CharField(default='Arial', max_length=50, verbose_name='Fonte')),
                ('margem_superior', models.IntegerField(default=20, verbose_name='Margem Superior (mm)')),
                ('margem_inferior', models.IntegerField(default=20, verbose_name='Margem Inferior (mm)')),
                ('margem_esquerda', models.IntegerField(default=20, verbose_name='Margem Esquerda (mm)')),
                ('margem_direita', models.IntegerField(default=20, verbose_name='Margem Direita (mm)')),
            ],
            options={
                'verbose_name': 'Configuração de Receituário',
                'verbose_name_plural': 'Configurações de Receituário',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='rqe',
            field=models.CharField(blank=True, help_text='Registro de Qualificação de Especialista.', max_length=20, verbose_name='RQE'),
        ),
    ]
