# Generated by Django 4.2.28 on 2026-05-05 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0002_receituarioconfig_medico_rqe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do plano')),
                ('tipo', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], help_text='Identificador interno do plano.', max_length=20, unique=True, verbose_name='Tipo')),
                ('descricao', models.TextField(blank=True, help_text='Descrição comercial para exibição.', verbose_name='Descrição')),
                ('preco_mensal', models.DecimalField(decimal_places=2, default=0, help_text='Preço mensal do plano. 0 = gratuito/trial.', max_digits=10, verbose_name='Preço mensal (R$)')),
                ('limite_transcricoes', models.IntegerField(default=20, help_text='0 = ilimitado.', verbose_name='Limite de transcrições/mês')),
                ('limite_assinaturas', models.IntegerField(default=30, help_text='0 = ilimitado.', verbose_name='Limite de assinaturas Gov.br/mês')),
                ('tem_dashboard_avancado', models.BooleanField(default=False, help_text='Libera gráficos de tempo médio e produtividade.', verbose_name='Dashboard avançado')),
                ('tem_suporte_prioritario', models.BooleanField(default=False, verbose_name='Suporte prioritário')),
                ('tem_multi_usuarios', models.BooleanField(default=False, help_text='Permite vários médicos na mesma conta (Enterprise).', verbose_name='Multi-usuários')),
                ('tem_relatorios_faturamento', models.BooleanField(default=False, verbose_name='Relatórios de faturamento')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar o plano (soft-delete).', verbose_name='Plano ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano de Assinatura',
                'verbose_name_plural': 'Planos de Assinatura',
                'ordering': ['preco_mensal'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('suspensa', 'Suspensa'), ('trial', 'Trial')], default='ativa', max_length=20, verbose_name='Status da assinatura')),
                ('transcricoes_usadas', models.PositiveIntegerField(default=0, verbose_name='Transcrições usadas no mês')),
                ('assinaturas_usadas', models.PositiveIntegerField(default=0, verbose_name='Assinaturas Gov.br usadas no mês')),
                ('ciclo_inicio', models.DateField(help_text='Data de início do período de faturamento.', verbose_name='Início do ciclo atual')),
                ('ciclo_fim', models.DateField(help_text='Data de término do período (próximo reset).', verbose_name='Fim do ciclo atual')),
                ('gateway_customer_id', models.CharField(blank=True, help_text='Ex: cus_xxxx (Stripe) ou customer_id (Mercado Pago).', max_length=200, verbose_name='ID do cliente no gateway')),
                ('gateway_subscription_id', models.CharField(blank=True, help_text='Ex: sub_xxxx (Stripe) ou preapproval_id (Mercado Pago).', max_length=200, verbose_name='ID da assinatura no gateway')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to='medico_app.medico', verbose_name='Médico')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assinaturas', to='medico_app.plano', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura do Médico',
                'verbose_name_plural': 'Assinaturas dos Médicos',
            },
        ),
    ]
