# Generated by Django 4.2.28 on 2026-05-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0003_planos_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Preço com desconto. Se preenchido, substitui o preço mensal.', max_digits=10, null=True, verbose_name='Preço Promocional (R$)'),
        ),
    ]
