# Generated by Django 4.2.28 on 2026-03-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='anamnese',
            field=models.TextField(blank=True, help_text='Estruturada automaticamente pela IA.', verbose_name='Anamnese'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='duracao_segundos',
            field=models.PositiveIntegerField(blank=True, help_text='Calculado automaticamente ao finalizar.', null=True, verbose_name='Duração da consulta (segundos)'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='hipotese_diagnostica',
            field=models.TextField(blank=True, help_text='Sugerida automaticamente pela IA.', verbose_name='Hipótese diagnóstica'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='queixa_principal',
            field=models.TextField(blank=True, help_text='Extraído automaticamente pela IA a partir da transcrição.', verbose_name='Queixa principal'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='transcricao_texto',
            field=models.TextField(blank=True, help_text='Texto transcrito da consulta. Áudio bruto NÃO é armazenado (LGPD).', verbose_name='Transcrição processada'),
        ),
    ]
