# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome fantasia')),
                ('razao_social', models.CharField(blank=True, max_length=200, verbose_name='Razão social')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('email_contato', models.EmailField(blank=True, max_length=254)),
                ('endereco', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinicas/logos/')),
                ('horario_funcionamento', models.CharField(blank=True, max_length=200)),
                ('ativa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
            },
        ),
        migrations.CreateModel(
            name='Secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('pode_agendar', models.BooleanField(default=True)),
                ('pode_ver_prontuario', models.BooleanField(default=False)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretarias', to='clinica_app.clinica')),
            ],
            options={
                'verbose_name': 'Secretaria',
                'verbose_name_plural': 'Secretarias',
            },
        ),
    ]
