# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaria',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'secretaria'}, on_delete=django.db.models.deletion.CASCADE, related_name='secretaria', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinica',
            name='medicos',
            field=models.ManyToManyField(blank=True, related_name='clinicas', to='medico_app.medico', verbose_name='Médicos da clínica'),
        ),
        migrations.AddField(
            model_name='clinica',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'clinica'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinica', to=settings.AUTH_USER_MODEL),
        ),
    ]
