# Generated by Django 4.2.28 on 2026-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='protocolo_manchester_ativo',
            field=models.BooleanField(default=False, verbose_name='Protocolo de Manchester na Fila'),
        ),
    ]
