# Generated by Django 4.2.28 on 2026-04-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica_app', '0003_clinica_protocolo_manchester_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinica',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude para geolocalização', null=True),
        ),
        migrations.AddField(
            model_name='clinica',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude para geolocalização', null=True),
        ),
    ]
