# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente_app', '0001_initial'),
        ('consulta_app', '0002_initial'),
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('codigo_cbhpm', models.CharField(blank=True, max_length=20, verbose_name='Código CBHPM')),
                ('requer_jejum', models.BooleanField(default=False)),
                ('instrucoes_preparo', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Exame',
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('solicitado', 'Solicitado'), ('realizado', 'Realizado'), ('resultado_disponivel', 'Resultado Disponível'), ('cancelado', 'Cancelado')], default='solicitado', max_length=30)),
                ('urgente', models.BooleanField(default=False)),
                ('instrucoes', models.TextField(blank=True)),
                ('resultado_arquivo', models.FileField(blank=True, null=True, upload_to='exames/resultados/')),
                ('resultado_texto', models.TextField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_realizacao', models.DateField(blank=True, null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exames_solicitados', to='consulta_app.consulta')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames_solicitados', to='medico_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exames', to='paciente_app.paciente')),
                ('tipo_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exame_app.tipoexame')),
            ],
            options={
                'verbose_name': 'Solicitação de Exame',
                'verbose_name_plural': 'Solicitações de Exame',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
