# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paciente_app', '0001_initial'),
        ('consulta_app', '0001_initial'),
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do template')),
                ('descricao', models.TextField(blank=True)),
                ('tipo_receita', models.CharField(choices=[('simples', 'Receita Simples'), ('controlada', 'Receita Controlada'), ('antimicrobiano', 'Antimicrobiano')], default='simples', max_length=20)),
                ('itens_json', models.JSONField(help_text='Snapshot serializado dos itens da receita.', verbose_name='Itens do template')),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates_receitas', to='medico_app.medico')),
            ],
            options={
                'verbose_name': 'Template de Receita',
                'verbose_name_plural': 'Templates de Receita',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simples', 'Receita Simples'), ('controlada', 'Receita Controlada'), ('antimicrobiano', 'Antimicrobiano')], max_length=20, verbose_name='Tipo de receita')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('emitida', 'Emitida'), ('assinada', 'Assinada Digitalmente'), ('enviada', 'Enviada ao Paciente'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], db_index=True, default='rascunho', max_length=20)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações clínicas')),
                ('data_emissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de emissão')),
                ('validade_dias', models.PositiveIntegerField(default=30, verbose_name='Validade (dias)')),
                ('hash_conteudo', models.CharField(blank=True, help_text='Hash do conteúdo serializado da receita para verificação de integridade.', max_length=64, verbose_name='Hash SHA-256 do conteúdo')),
                ('hash_verificacao', models.CharField(blank=True, db_index=True, help_text='Token público para verificação via QR Code (não contém dados sensíveis).', max_length=64, null=True, unique=True, verbose_name='Hash de verificação pública')),
                ('assinatura_govbr', models.BinaryField(blank=True, help_text='Assinatura PAdES retornada pela API de assinatura digital do Gov.br.', null=True, verbose_name='Assinatura PAdES Gov.br')),
                ('via_govbr', models.BooleanField(default=False, verbose_name='Assinada via Gov.br')),
                ('assinada_em', models.DateTimeField(blank=True, null=True, verbose_name='Data/hora da assinatura digital')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='receitas/pdfs/', verbose_name='PDF da receita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receitas', to='consulta_app.consulta', verbose_name='Consulta de origem')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='medico_app.medico', verbose_name='Médico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to='paciente_app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=200, verbose_name='Nome comercial')),
                ('principio_ativo', models.CharField(max_length=200, verbose_name='Princípio ativo')),
                ('concentracao', models.CharField(blank=True, max_length=100, verbose_name='Concentração')),
                ('forma_farmaceutica', models.CharField(blank=True, help_text='Ex: comprimido, cápsula, solução injetável', max_length=100, verbose_name='Forma farmacêutica')),
                ('tipo', models.CharField(choices=[('simples', 'Receita Simples'), ('controlado', 'Receita Controlada (C1, C2)'), ('antimicrobiano', 'Antimicrobiano (AM)')], default='simples', max_length=20)),
                ('registro_anvisa', models.CharField(blank=True, max_length=50, verbose_name='Registro ANVISA')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome', 'principio_ativo'], name='prescricao__nome_489abc_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosagem', models.CharField(max_length=100, verbose_name='Dosagem')),
                ('quantidade', models.CharField(max_length=50, verbose_name='Quantidade')),
                ('posologia', models.TextField(verbose_name='Posologia / Modo de usar')),
                ('via_administracao', models.CharField(blank=True, help_text='Ex: oral, intravenoso, tópico', max_length=50, verbose_name='Via de administração')),
                ('duracao_tratamento', models.CharField(blank=True, help_text='Ex: 7 dias, 30 dias, uso contínuo', max_length=50, verbose_name='Duração do tratamento')),
                ('instrucoes_especiais', models.TextField(blank=True, help_text='Alertas, jejum, interações medicamentosas, etc.', verbose_name='Instruções especiais')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem na receita')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_receita', to='prescricao_app.medicamento', verbose_name='Medicamento')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='prescricao_app.receita', verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Item de Receita',
                'verbose_name_plural': 'Itens de Receita',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['medico', 'status'], name='prescricao__medico__876ddd_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['paciente', 'status'], name='prescricao__pacient_da70fb_idx'),
        ),
        migrations.AddIndex(
            model_name='receita',
            index=models.Index(fields=['hash_verificacao'], name='prescricao__hash_ve_d1540d_idx'),
        ),
    ]
