# Generated by Django 4.2.28 on 2026-04-10 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_app', '0003_paciente_altura_cm_paciente_peso_kg'),
        ('prescricao_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tomado_em', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora em que marcou como tomado')),
                ('dose_referencia', models.DateTimeField(blank=True, help_text='Horário planejado para a dose (calculado pela posologia).', null=True, verbose_name='Horário de referência da dose')),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('item_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='prescricao_app.itemreceita', verbose_name='Item da Receita')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_medicamento', to='paciente_app.paciente', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Check-in de Medicamento',
                'verbose_name_plural': 'Check-ins de Medicamentos',
                'ordering': ['-tomado_em'],
            },
        ),
    ]
