# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome completo')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('medico', 'Médico'), ('paciente', 'Paciente'), ('secretaria', 'Secretaria'), ('clinica', 'Clínica')], db_index=True, max_length=20, verbose_name='Perfil de acesso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('is_verified', models.BooleanField(default=False, help_text='True quando o email foi confirmado.', verbose_name='Email verificado')),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de cadastro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último acesso')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('cpf', models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('genero', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informar', 'Prefiro não informar')], max_length=20)),
                ('endereco_logradouro', models.CharField(blank=True, max_length=200)),
                ('endereco_numero', models.CharField(blank=True, max_length=20)),
                ('endereco_complemento', models.CharField(blank=True, max_length=100)),
                ('endereco_bairro', models.CharField(blank=True, max_length=100)),
                ('endereco_cidade', models.CharField(blank=True, max_length=100)),
                ('endereco_estado', models.CharField(blank=True, max_length=2)),
                ('endereco_cep', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
