# Generated by Django 4.2.28 on 2026-03-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cpf',
            field=models.CharField(blank=True, help_text='Formato: 000.000.000-00', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
