# Generated by Django 4.2.28 on 2026-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_userprofile_cpf_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Ativa a camada extra de segurança no login.', verbose_name='Autenticação em Duas Etapas (2FA)'),
        ),
    ]
