# Generated by Django 4.2.28 on 2026-02-27 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medico_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('tipo_sanguineo', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias conhecidas')),
                ('medicamentos_uso_continuo', models.TextField(blank=True)),
                ('convenio_nome', models.CharField(blank=True, max_length=100, verbose_name='Convênio')),
                ('convenio_numero', models.CharField(blank=True, max_length=50, verbose_name='Número do plano')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_principals', to='medico_app.medico')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'paciente'}, on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='Prontuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(verbose_name='Data da consulta')),
                ('queixa_principal', models.TextField(verbose_name='Queixa principal')),
                ('anamnese', models.TextField(blank=True, verbose_name='Anamnese')),
                ('exame_fisico', models.TextField(blank=True, verbose_name='Exame físico')),
                ('hipotese_diagnostica', models.TextField(blank=True, verbose_name='Hipótese diagnóstica')),
                ('diagnostico_cid10', models.CharField(blank=True, max_length=10, verbose_name='CID-10')),
                ('conduta', models.TextField(blank=True, verbose_name='Conduta médica')),
                ('retorno_em', models.DateField(blank=True, null=True, verbose_name='Data do retorno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prontuarios_criados', to='medico_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prontuarios', to='paciente_app.paciente')),
            ],
            options={
                'verbose_name': 'Prontuário',
                'verbose_name_plural': 'Prontuários',
                'ordering': ['-data_consulta'],
            },
        ),
    ]
