# Generated by Django 4.2.28 on 2026-03-19 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='doencas_cronicas',
            field=models.TextField(blank=True, help_text='(Armazenamento sensível com criptografia extra simulada na camada DB)', verbose_name='Doenças crônicas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notificacoes_email',
            field=models.BooleanField(default=True, verbose_name='Notificações via E-mail'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='notificacoes_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Notificações via WhatsApp'),
        ),
    ]
