# Generated by Django 4.2.28 on 2026-03-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente_app', '0002_paciente_doencas_cronicas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='altura_cm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)'),
        ),
    ]
