# Generated by Django 4.2.28 on 2026-04-10 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medico_app', '0002_receituarioconfig_medico_rqe'),
        ('paciente_app', '0003_paciente_altura_cm_paciente_peso_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_preferencia', models.DateField(verbose_name='Data preferida')),
                ('periodo_preferencia', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=20, verbose_name='Período')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo resumido')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita (Agendada)'), ('recusada', 'Recusada'), ('novo_horario', 'Novo Horário Sugerido')], default='pendente', max_length=20, verbose_name='Status da solicitação')),
                ('resposta_clinica', models.TextField(blank=True, verbose_name='Resposta/Justificativa da Clínica')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_recebidas', to='medico_app.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_consulta', to='paciente_app.paciente')),
            ],
            options={
                'verbose_name': 'Solicitação de Consulta',
                'verbose_name_plural': 'Solicitações de Consulta',
                'ordering': ['-created_at'],
            },
        ),
    ]
